In [1]:
## Imports
from __future__ import print_function

import torch
from torch import optim
from torch.utils.data import DataLoader
import torch.nn as nn

from unet.unet_model import RegressorUNet
from unet.unet_parts import SegmentationRegressionLoss

from utils.dataset import CrossValDataset
from utils.model_eval import dice_coefficient
from utils.data import RegressorDataset

from torch.utils.tensorboard import SummaryWriter

import numpy as np

In [2]:
## Device
if torch.cuda.is_available():
    device = 'cuda'
    print('Using GPU')
else:
    device = 'cpu'
    print('Using CPU')

Using GPU


In [3]:
## Load Model
modelpath = "D:/autopos/nets/unet-crop-save3_9.pth"
pretrained_model = torch.load(modelpath, map_location='cpu')

In [4]:
## Dataset
groupPath  = "D:/autopos/train"
originPath = "D:/autopos/train/origin.csv"
batch_size = 4

## Training
n_channels = 1
n_classes = 13
n_regress = 2
# n_bottle = 256
# n_hidden = [512,256,128,64,32,16]
# n_hidden = [512,256]
# n_hidden = [1024,1024,512,512,256,256]
n_reduce = [64,128]
n_hidden = [256,256,256]
img_size = 512

learning_rate = 1e-3
weight_decay  = 1e-8
momentum      = 0.9

num_epochs    = 41

##Cropping
D = 350
N = 512
xc=0
yc=0
centermode = 'rand'
mu = np.array([0,0])
sigma= 50

In [ ]:
## Train
fullDirList = np.array([groupPath+"/group_00",groupPath+"/group_01",groupPath+"/group_02",groupPath+"/group_03",groupPath+"/group_04"])
inds = np.arange(len(fullDirList))
for partition in range(len(fullDirList)):
# for partition in range(1):
    trainInd = np.delete(inds,[partition])
    testInd  = inds[partition]
    trainDirs = fullDirList[trainInd]
    testDir   = [fullDirList[testInd]]
    
    trainDataset = RegressorDataset([x + "/img" for x in trainDirs], [x + "/seg" for x in trainDirs], originPath,D=D,N=N,xc=xc,yc=yc,centermode=centermode,mu=mu,sigma=sigma)
    testDataset  = RegressorDataset([x + "/img" for x in testDir],   [x + "/seg" for x in testDir],   originPath,D=D,N=N,xc=xc,yc=yc,centermode=centermode,mu=mu,sigma=sigma)
    
    trainLoader  = DataLoader(trainDataset,batch_size=batch_size)
    testLoader   = DataLoader(testDataset,batch_size=batch_size)
    
    # Define Net
#     net = RegressorUNet(n_channels=n_channels, n_classes=n_classes,n_regress=n_regress,n_hidden=n_hidden,n_bottle=n_bottle,img_size=img_size)
#     net.to(device=device)
#     net.apply_state_dict(pretrained_model)
    
#     net = RegressorNet(n_channels=n_channels, n_regress=n_regress,n_hidden=n_hidden,n_bottle=n_bottle,img_size=img_size)
#     net = RegressorNet(n_channels=n_channels, n_regress=n_regress,n_hidden=n_hidden,img_size=img_size)
    net = RegressorUNet(n_channels,n_classes,n_reduce,n_hidden,n_regress,img_size)
    print(net)
    net.apply_state_dict(pretrained_model)
    net.to(device=device)
    
    
    print("Successfully loaded pretrained model")
    
    # Optimizer
    optimizer  = optim.RMSprop(net.parameters(),lr = learning_rate, weight_decay = weight_decay, momentum = momentum)
#     critereon  = SegmentationRegressionLoss()  
    critereon = nn.MSELoss()
#     lossweight = 100 
    
    #Tensorboard
    writer = SummaryWriter('runs/regress_model5_partition_'+str(partition))
    
    for epoch in range(num_epochs):
        net.train()
        epoch_train_loss = 0
        for trainIndex,batch in enumerate(trainLoader,0):
            imgs = batch['img']
#             segs_gt = batch['seg']
            regs_gt = batch['org']
            
            imgs = imgs.to(device=device, dtype=torch.float32)
#             segs_gt = segs_gt.to(device=device, dtype = torch.long)
            regs_gt = regs_gt.to(device=device, dtype = torch.float32)
            
#             segs_pr,regs_pr = net(imgs)
            regs_pr = net(imgs)
            
#             loss = critereon(segs_pr,regs_pr,segs_gt,regs_gt,lossweight)
            loss = critereon(regs_pr,regs_gt)
            
            epoch_train_loss += loss.item()/len(trainLoader)
            
            regs_err = regs_pr-regs_gt
            print(regs_err)
            
            optimizer.zero_grad()
            loss.backward()
#             nn.utils.clip_grad_value_(net.parameters(),0.1)
            optimizer.step()
            
            print("Train: " + str(loss.item()))
            
        writer.add_scalar('Training Loss',
                        epoch_train_loss,
                        epoch)
        
        net.eval()
        epoch_test_loss = 0
        for testIndex,batch in enumerate(testLoader,0):
            imgs = batch['img']
#             segs_gt = batch['seg']
            regs_gt = batch['org']
            
            imgs = imgs.to(device=device, dtype=torch.float32)
#             segs_gt = segs_gt.to(device=device, dtype = torch.long)
            regs_gt = regs_gt.to(device=device, dtype = torch.float32)
            
#             segs_pr,regs_pr = net(imgs)
            regs_pr = net(imgs)
            
#             loss = critereon(segs_pr,regs_pr,segs_gt,regs_gt,lossweight)
            loss = critereon(regs_pr,regs_gt)
    
            epoch_test_loss += loss.item()/len(testLoader)
            
            regs_err = regs_pr-regs_gt
            print(regs_err)
            
            print("Test: " + str(loss.item()))
            
        writer.add_scalar('Validation Loss',
                        epoch_test_loss,
                        epoch)
        
#         savefile = "D:\\autoseg\\nets\\unet-save" + str(partition) + "_" + str(epoch) + ".pth"
#         torch.save(net.state_dict(),savefile)


RegressorUNet(
  (inc): DoubleConv(
    (double_conv): Sequential(
      (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU(inplace=True)
      (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (4): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU(inplace=True)
    )
  )
  (down1): Down(
    (maxpool_conv): Sequential(
      (0): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (1): DoubleConv(
        (double_conv): Sequential(
          (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-0

Train: 3606859.0
tensor([[ -981.9326, -1371.0845],
        [ -429.5708,  -813.5112],
        [-1512.1472, -1844.8693],
        [-1467.8289, -1796.7218]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1845407.375
tensor([[1004.2398,   59.6421],
        [1470.7819,  442.0633],
        [1762.7042,  734.6041],
        [1213.9565,  164.5981]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1064778.25
tensor([[3760.2322, 1711.4484],
        [5604.1387, 1470.6372],
        [3942.5359, 2153.2178],
        [4360.3433, 2028.6736]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 11743199.0
tensor([[-4464.3296, -3248.1340],
        [-5351.9897, -3982.2139],
        [-5485.4141, -4065.5339],
        [-4302.0396, -3118.7170]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 18729338.0
tensor([[ -397.2887,  -625.2198],
        [  -71.3799,   -94.6945],
        [ -332.6841, -1086.5721],
        [ -160.0299,  -140.9780]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 237450.296875
tensor([[ 142.1

Train: 3160.29931640625
tensor([[  -4.8857,  118.2233],
        [  20.6406,  137.6860],
        [ 167.9034, -170.2905],
        [ -98.6968, -135.7072]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 14841.5
tensor([[-31.7575,  74.9860],
        [ 27.9841, 131.4890],
        [ 12.7735, 111.5299]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 6217.66552734375
tensor([[ -15.7053,   82.9492],
        [   2.5181, -360.3015],
        [-573.1040,  661.8323],
        [  91.0449,  -33.2163]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 114101.671875
tensor([[-68.7996,  89.6611],
        [155.3784,  -8.6091],
        [132.6371, -31.3557],
        [ 93.8829, 111.9342]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 9613.51171875
tensor([[  8.7222,  29.4734],
        [ 54.7944, 113.2808],
        [-58.5682,  31.4787],
        [ 63.9812, -88.0890]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 4131.765625
tensor([[  47.9550,   79.9591],
        [ -35.7481,  124.2819],
        [-128.3585,

Train: 3508.51171875
tensor([[ 51.6202, 113.3679],
        [-73.5327, -19.7308],
        [ 11.5643, -35.6211],
        [ 13.9910, 111.2031]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 4409.71923828125
tensor([[-28.8376,  63.0252],
        [-66.0716, 104.9672],
        [ 42.2105,  61.3093],
        [ 26.2297, 142.5937]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 5843.60888671875
tensor([[-56.9508, -40.2290],
        [ 47.9605,  -6.0887],
        [-63.5646,   6.2784],
        [-84.3858, -96.3307]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 3459.93798828125
tensor([[ -91.1277, -127.4861],
        [ -12.8293,  -52.7941],
        [ -21.0077, -136.6928],
        [ -25.0717,  -17.5286]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 5946.3583984375
tensor([[-21.4345, 118.4451],
        [  6.1305,  42.4051],
        [-32.5323,  69.3937],
        [ 29.2862, -72.7478]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 3543.526123046875
tensor([[ 24.3295,  28.8152],
        [ -

tensor([[ -5.6684, -19.0024],
        [-31.2622,  41.1608],
        [  6.1949,  95.7231],
        [  6.4910,  17.5687]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1577.105224609375
tensor([[ 27.4917, -25.8106],
        [ 23.7352,  44.0488],
        [ 50.7577,  33.0084],
        [ -2.7826,  60.8791]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1413.1925048828125
tensor([[-0.4385, 36.2247],
        [31.2021, 29.5581],
        [42.5902, 55.5927]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1344.02490234375
tensor([[ -6.1607,  19.5555],
        [-11.8167,  38.2980],
        [ 19.3548,  99.9610],
        [-41.0768,  16.2280]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 1793.02587890625
tensor([[-28.9466, -56.4688],
        [ 35.2710,  83.3095],
        [  0.9482, -58.7166],
        [  4.9319,   7.5195]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 1967.568603515625
tensor([[  8.4818,  44.3542],
        [ 44.6242, 154.4050],
        [ 46.7205,  79.6759],
        [-58.3

Train: 4100.44921875
tensor([[-10.2561,  73.6806],
        [  6.6850,  43.6452],
        [ 29.2752,  18.9592],
        [-47.2130,  54.2530]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1734.070068359375
tensor([[ 37.6465,  22.8291],
        [-51.8653,   9.7901],
        [-18.6187, -25.0867],
        [-39.4027,  21.1092]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 962.3072509765625
tensor([[ 35.8033,  47.3275],
        [ -2.2385,  -2.1489],
        [ 42.9398, -20.2630],
        [ 58.0835,  73.1897]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1814.53173828125
tensor([[   4.0844,  -11.0847],
        [  51.0932, -148.5255],
        [ -38.9635,  -18.3550],
        [  -7.3703,  -28.6081]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 3442.2138671875
tensor([[ 14.3970, -35.7055],
        [ 22.7155,  63.7785],
        [ 40.7245, -39.6105],
        [ 18.2251, -78.0356]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1964.379638671875
tensor([[ -1.9763,  30.3620],
        [

tensor([[-11.2310,  30.1335],
        [ 30.0952, -73.7736],
        [-29.2902,  -9.6977],
        [ 33.0096,  70.3008]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1795.777587890625
tensor([[-11.1099,  15.0248],
        [ 52.7557,  30.1126],
        [-48.3312,  58.9411],
        [ 40.0375, -55.4663]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1816.074462890625
tensor([[-55.3284,   6.4330],
        [-68.5267, -16.7728],
        [  9.2437,   0.2370],
        [-21.3761, -21.4796]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1135.45703125
tensor([[-45.3793,  -9.8336],
        [-42.3431, -51.6891],
        [ -7.0249,  30.8128]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1269.908203125
tensor([[  0.6263,  29.2246],
        [-34.6599,  28.6945],
        [-29.4395, -11.5913],
        [ 69.5469, -55.2303]], device='cuda:0', grad_fn=<SubBackward0>)
Test: 1470.9183349609375
tensor([[  70.8207,  -19.6087],
        [  -2.5260,  -10.5275],
        [  42.5379, -175.5901],
      

Train: 972.7888793945312
tensor([[ 13.2785, -48.3956],
        [-65.2268,  46.0057],
        [-31.4539,  70.3633],
        [-46.2877,  46.4086]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2390.76953125
tensor([[ -7.2483,  -5.2539],
        [-53.3361,   1.6710],
        [-22.2794,  23.1355],
        [ 11.4341, -14.5249]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 537.625732421875
tensor([[-30.9592,  11.7970],
        [ 33.6485, -18.7461],
        [-27.9894, -12.5665],
        [-25.9877,   0.3397]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 524.75927734375
tensor([[  9.8992,   6.5670],
        [-10.2855,  -4.1892],
        [ -7.1099, -42.7389],
        [ 51.3660, -17.1690]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 634.3587646484375
tensor([[ -3.0022, -33.5602],
        [ 74.6026, -54.0750],
        [ 30.6694, -31.6951],
        [ -3.8427, -41.8508]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1667.0499267578125
tensor([[ -4.6309,  18.8934],
        [ 67.568

tensor([[  3.5896,  52.6371],
        [-36.9371, -13.5600],
        [ 17.3051, -49.4786],
        [-13.8235,  29.6349]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1018.58544921875
tensor([[ 17.3500,  42.7766],
        [ 24.1708, -19.9693],
        [ 30.4959,  35.2211],
        [-37.0035,  13.7423]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 855.3132934570312
tensor([[-25.3838, -16.2770],
        [ 21.7067,  29.4645],
        [-19.7314,  30.4233],
        [ 28.8989, -24.8047]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 626.7432861328125
tensor([[ 1.5645e+01,  1.0303e+01],
        [-8.5632e+01,  5.3107e+01],
        [ 1.2474e+01,  1.7867e+01],
        [-1.0604e+01,  5.5946e-02]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1386.4404296875
tensor([[-94.6253, -13.9012],
        [-98.2229, -30.7323],
        [-55.7856,  71.7902]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 4667.54833984375
tensor([[-42.1305,  13.6390],
        [-61.0810, -34.2978],
        [ 13.05

Train: 1214.3759765625
tensor([[-57.8342, -34.8579],
        [  7.5841,   4.1052],
        [ -9.1853, -58.0413],
        [-35.5359, -19.6874]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1217.223876953125
tensor([[-29.1981, -22.9204],
        [ 16.5779, -19.7876],
        [ -0.0366,  11.4298],
        [-20.1499,   5.7291]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 326.7171630859375
tensor([[ 6.4604, 17.8097],
        [37.0627, 18.2440],
        [48.5022, 31.7781],
        [16.9545, 36.7308]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 883.0401611328125
tensor([[ 25.9002,  42.0490],
        [-36.2417,  14.1690],
        [-15.6086,  30.1682],
        [ -9.9752,  -5.1113]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 654.0669555664062
tensor([[-14.8304,  45.9936],
        [-45.7769,  27.8146],
        [ 32.2409,  22.9800],
        [ 43.4034,  82.5846]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1934.5184326171875
tensor([[-37.9214,  16.9737],
        [-21.3381, 

Train: 1351.6529541015625
tensor([[-40.6651,  -9.9515],
        [-24.8724, -27.0193],
        [ 44.6435, -16.1387],
        [ 39.0291,  -0.7918]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 859.8450927734375
tensor([[-32.4033,   3.7734],
        [ 28.5520, -16.7110],
        [  2.8159,  26.6353],
        [-20.9683,  41.7724]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 632.58251953125
tensor([[-35.7071, -10.6843],
        [ 56.0435,  17.2113],
        [ 15.1058,  18.6085],
        [ 48.7440, -24.9476]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1049.8836669921875
tensor([[ -7.6864,   6.4807],
        [-39.4405,  32.7887],
        [ 61.9744,  58.6917],
        [ 17.9557,  13.0890]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1313.8765869140625
tensor([[-57.5842,  26.3950],
        [-14.0078, -14.2827],
        [ 39.4730,  55.2869]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1504.6009521484375
tensor([[ 13.5395, -18.3666],
        [ -9.4525, -11.2627],
        

Train: 1496.24853515625
tensor([[51.8037, 20.4535],
        [ 3.0255, 22.5547],
        [32.4718, 12.3553],
        [ 0.1255,  6.5224]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 608.68359375
tensor([[-13.6404,  -0.8085],
        [  3.6632,  14.9317],
        [-15.2133,   1.8776],
        [ 12.6037,  18.2053]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 143.54299926757812
tensor([[ 40.8411,  -0.1906],
        [ 51.5899, -40.4002],
        [ 29.0263, -35.4617],
        [ 35.8858,   3.4601]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1170.1934814453125
tensor([[ -7.5687,  -3.5804],
        [ 17.3971, -10.1607],
        [-25.6761,  -4.7476],
        [ -1.5971, -23.8338]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 216.05039978027344
tensor([[-5.9645e+01, -8.7814e-03],
        [-4.3101e+01,  7.1198e+00],
        [-2.6916e+01,  7.2897e+00],
        [-4.1857e+01,  3.0077e+01]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1112.5299072265625
tensor([[  3.7718, -21.994

tensor([[ -1.2503, -17.6023],
        [-13.6365,  -0.0265],
        [  9.2244, -13.3173],
        [-14.9072,   3.1947]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 124.02857971191406
tensor([[-54.2633,  18.1792],
        [ 26.3765,  28.2181],
        [-65.7590,   5.0409],
        [-51.6323,  14.9419]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1500.723876953125
tensor([[ -2.6648,  19.9544],
        [-43.2419,  40.7440],
        [ 16.4949,  21.0277],
        [ 37.0339,  28.9028]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 857.0411376953125
tensor([[-25.8329,  34.4095],
        [ 31.8656,  27.4559],
        [-36.3109,  30.1631],
        [-15.2078, -13.6850]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 783.4307250976562
tensor([[-15.8434,  28.6158],
        [-36.3021,   0.7003],
        [ 26.5140,  22.3304],
        [-26.2103,  15.9740]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 566.5001220703125
tensor([[ 59.4527,  -5.6469],
        [ 30.4403, -25.8266],
    

Train: 797.6815185546875
tensor([[ 44.5274,  22.8677],
        [-56.3852,   4.7413],
        [ 27.7063,  32.4882],
        [ 16.1253,  22.9992]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1039.93798828125
tensor([[-29.9920,  18.2785],
        [ 12.8112,   9.9428],
        [ -2.1647,  20.4580],
        [-21.5673,   7.1668]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 304.542236328125
tensor([[-60.1326, -11.3728],
        [ 19.4388,  -6.1415],
        [-44.9583, -15.7635],
        [ -9.4204, -25.1539]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 894.008056640625
tensor([[-42.4301, -17.4704],
        [ -5.5227, -16.6464],
        [-25.1117,   0.3985],
        [  0.6949, -16.9007]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 416.25048828125
tensor([[-45.6748,  -3.9247],
        [-26.4437,  16.3836],
        [ -2.4908,   4.8937],
        [  7.0456,  -5.6791]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 397.6666259765625
tensor([[ 22.1217,  -5.3478],
        [ 19.89

Train: 1214.342041015625
tensor([[-10.0014, -30.1845],
        [-70.8893, -32.0988],
        [-53.9060, -11.5212],
        [-41.1163, -17.4636]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1512.609130859375
tensor([[-13.0553,   4.3319],
        [ -6.0938, -15.1504],
        [ -1.2193, -28.9543],
        [-48.1180,   9.2282]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 462.0267028808594
tensor([[-14.0281,  12.0456],
        [ 43.5999,  -3.5328],
        [-42.9033,   8.7813],
        [  2.2589,  21.8897]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 582.1722412109375
tensor([[-34.6875,  20.1586],
        [-23.4444,  45.8725],
        [ 24.7401,  46.5478],
        [ -9.0045,  13.1991]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 912.1990966796875
tensor([[ 35.1844,  17.3280],
        [-44.3557,  48.3730],
        [ 64.6757,  58.2149],
        [ 33.0789,  27.4782]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1908.345703125
tensor([[-27.1780,  -1.3317],
        [ 16.

Train: 1148.7197265625
tensor([[  7.4509,  20.3728],
        [  4.8254,   5.5565],
        [-42.2902,  13.2482],
        [  1.0173,  14.5176]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 337.561767578125
tensor([[ -6.2500,  -2.5651],
        [-34.3066,  23.1985],
        [  1.4580, -12.4453],
        [-30.1693, -12.5672]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 373.23529052734375
tensor([[ 24.6112, -25.1799],
        [-45.3499, -22.5386],
        [-47.2293, -20.4766],
        [ 36.4383, -37.7198]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1150.59619140625
tensor([[-53.8310,  10.2044],
        [  9.3600, -26.5046],
        [ 35.6568,  -5.7751],
        [-47.2727, -27.0323]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1007.7776489257812
tensor([[ 51.5885, -15.4493],
        [ 39.0297, -22.1660],
        [ -7.3037, -15.8532],
        [-36.7468,  -2.1412]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 821.7855834960938
tensor([[ 19.5719,  24.9568],
        [-33

Train: 1647.3896484375
tensor([[ -9.3778,  -1.0200],
        [-39.3541,  12.4507],
        [ 14.6907,   1.6535],
        [ -2.0224,  13.0677]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 273.2688293457031
tensor([[-61.2185,  29.7395],
        [ 38.7864,  19.1667],
        [ 38.1262,   6.4614],
        [ 28.7435,  20.1721]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1154.0439453125
tensor([[ -6.1126, -10.6926],
        [ 41.3756, -18.8604],
        [ 14.5700, -19.4099],
        [-24.2273,  22.4669]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 487.513427734375
tensor([[  3.8735, -10.1407],
        [ 16.9522,  15.8478],
        [ 17.3170,   7.7501],
        [ 63.6599,   6.8073]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 639.4041137695312
tensor([[ 55.5474, -15.4667],
        [ -1.3165,  -0.7035],
        [-13.8153,  -8.9931],
        [ 52.3414,   2.7838]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 793.2589111328125
tensor([[-45.5694,  -4.2108],
        [ 10.19

Train: 1602.4228515625
tensor([[-19.9845,  12.8701],
        [-42.1485,   5.7359],
        [  5.1025,   7.1027],
        [ -0.6421,  18.0676]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 347.21826171875
tensor([[-38.8083, -13.4265],
        [-28.4135,  -6.4922],
        [ 22.6333, -11.1429],
        [ 36.9418,   0.3485]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 567.1351928710938
tensor([[ 21.3962, -19.2336],
        [-53.6953, -13.3094],
        [-28.3058, -30.4133],
        [ 34.7701, -13.2722]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 874.9190673828125
tensor([[-17.1059, -19.3163],
        [  1.1399, -17.6850],
        [ 53.0158, -45.6427],
        [ -4.7764, -28.7296]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 840.24072265625
tensor([[ 38.2992,   7.6202],
        [ -5.2453, -21.1269],
        [-14.0907,   0.4793],
        [ -2.3879, -12.5078]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 294.9598388671875
tensor([[-37.9262,  12.2605],
        [-43.211

Train: 982.58203125
tensor([[-30.0606, -23.0256],
        [-24.9461, -43.1713],
        [ -2.4317, -21.1508],
        [ -8.7129, -28.9552]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 660.93359375
tensor([[ 36.3360, -15.3747],
        [ 45.2434, -42.8219],
        [ 46.8568, -20.4450],
        [-19.3904, -26.0105]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1137.9322509765625
tensor([[25.3113,  3.4520],
        [20.8125, -3.5792],
        [21.3798, 15.8971],
        [-9.2318, 10.5256]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 250.5470733642578
tensor([[11.9509, 71.6183],
        [17.6822, 78.2277],
        [ 4.1662, 27.1149],
        [ 0.4611, 45.3199]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1813.865234375
tensor([[-50.1716,  16.2433],
        [-28.0322, -23.1466],
        [ 27.2278,   8.9187],
        [  3.2305, -13.0834]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 638.1390991210938
tensor([[-50.2952, -32.8848],
        [  7.5457, -93.7603],
        

Train: 871.168212890625
tensor([[-25.5770,  30.1634],
        [ 10.2116,  -8.5164],
        [-13.9052,  34.4102],
        [  4.4163,  -7.3676]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 399.00274658203125
tensor([[  8.0273, -29.5275],
        [  6.8700, -20.3264],
        [-16.5898, -34.0014],
        [ -5.1370, -35.5819]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 515.0552978515625
tensor([[  4.1414,  -3.8673],
        [ -1.6958, -17.2761],
        [ 66.6746,  -8.8752],
        [ 50.5035, -24.2091]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 999.3001708984375
tensor([[-20.1799,  -9.8963],
        [ 57.4870,  -6.6914],
        [ 47.3250, -21.0531],
        [  6.5495,  -3.0555]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 823.7271728515625
tensor([[-26.1230,  26.8866],
        [-49.1048,  17.2286],
        [  5.1909,  16.5916],
        [ 39.8622,  21.6848]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 809.3573608398438
tensor([[  0.2485,  27.1362],
        [-

Train: 1297.46826171875
tensor([[-36.3936, -18.7681],
        [ 26.9647,  13.4992],
        [-37.0838,  29.5835],
        [ 38.6077,  27.0743]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 882.5021362304688
tensor([[ 28.7661,  36.8047],
        [-11.6076, -13.3456],
        [ 54.0160,  14.7315],
        [ 47.0782,   5.8401]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 985.0152587890625
tensor([[ 48.9637,  -7.0165],
        [-22.9132,  20.1199],
        [-14.6547,  12.8443],
        [ 56.4178,  12.1715]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 885.9189453125
tensor([[ 23.4800,  -2.1037],
        [  7.9659,   7.9088],
        [ 29.6650,  -3.0464],
        [ 34.1086, -44.4842]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 589.1592407226562
tensor([[ 15.6246,   8.4835],
        [-58.4370,  13.9612],
        [ 74.9281, -25.1991],
        [ 63.9390,   7.2468]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1789.477783203125
tensor([[-31.4237,  20.3774],
        [-54.3

Train: 1456.9501953125
tensor([[14.3931, 28.9345],
        [45.7990, 13.9601],
        [38.0868, 16.6501],
        [ 8.4862,  9.3816]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 653.0831298828125
tensor([[ 11.3884,   6.9717],
        [ 40.3712,  14.8935],
        [ 19.1482,   1.8898],
        [ 48.3723, -25.1695]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 671.695556640625
tensor([[-47.7009, -27.6211],
        [ 37.6816, -27.7562],
        [ 46.5681, -21.9141],
        [-41.2578, -42.1979]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1420.036865234375
tensor([[  8.2602, -15.2950],
        [-50.8660, -19.1949],
        [ 49.8953, -29.1226],
        [-46.0655,   4.4662]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1092.2010498046875
tensor([[-26.0529,  -2.7801],
        [-60.6787,   6.8919],
        [-28.7831,   1.1121],
        [-53.0594,   1.2164]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1007.7957763671875
tensor([[ 32.7652,  27.0456],
        [-20.5831, 

Train: 1530.447021484375
tensor([[ -8.4741,  -2.4504],
        [  9.4417, -33.1730],
        [ 52.3704,  -4.0552],
        [  6.6315, -30.1404]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 622.3665771484375
tensor([[ 78.3759,  -0.1627],
        [ 52.6397, -16.5099],
        [-12.3355, -22.7310],
        [ 61.0864, -12.3829]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1717.509033203125
tensor([[39.5225,  2.6208],
        [69.1251, 37.2361],
        [69.1355, 18.1276],
        [83.4202, 51.6274]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2808.29541015625
tensor([[-12.7478,  35.3511],
        [ 56.1667,  51.9893],
        [ 51.2065,  64.5355],
        [ 31.5245,  51.8539]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2217.418701171875
tensor([[-37.2231,  45.9545],
        [-46.2840,  39.6742],
        [ -0.4077,  40.3056],
        [-18.2494,  36.5228]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1313.160400390625
tensor([[  1.0873, -12.4763],
        [-39.2485, 

Train: 765.007568359375
tensor([[  8.8088,  33.2759],
        [-60.5129,  26.2085],
        [ 31.2349,  27.3541],
        [-64.7752,  53.9191]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1795.0672607421875
tensor([[-38.5723,  73.5028],
        [-27.8038,  59.9093],
        [-25.4936,  55.2003],
        [  4.9979,  29.3703]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1979.656005859375
tensor([[ 16.0545,  35.6881],
        [-24.2131,  72.1369],
        [  2.3123,  33.9063],
        [-26.1797,  49.3584]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1449.751953125
tensor([[55.1547, -0.4290],
        [32.2845,  8.9823],
        [30.3649, -0.9821],
        [ 9.7261, -4.3561]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 650.2203979492188
tensor([[ 42.8307,  14.3929],
        [  4.3763, -47.7987],
        [ 45.8858, -18.1345],
        [ 15.2890,   0.7102]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 876.764892578125
tensor([[-45.5066, -36.6922],
        [-56.0584, -18

Train: 3170.62646484375
tensor([[42.8243,  7.6867],
        [65.4744, 47.9813],
        [22.1228, 53.6389],
        [44.2550, 35.1036]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1879.927734375
tensor([[64.2243, 37.2394],
        [ 6.1042, -4.7740],
        [42.7309, 25.4485],
        [-2.0937, 23.7282]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1076.568603515625
tensor([[-30.6759, -14.1844],
        [-30.2457,  19.0524],
        [ 27.6546,   0.1506],
        [ 52.3923,  12.4393]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 760.5619506835938
tensor([[-45.9891, -84.9284],
        [-18.3241, -54.8825],
        [  8.7775, -33.9440],
        [-30.0457, -87.8084]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2814.74951171875
tensor([[-16.0750,  40.5259],
        [-58.6805,  44.9836],
        [-29.5376,   8.9930],
        [ 42.8171,  47.1932]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1547.69091796875
tensor([[-44.1216,  35.5171],
        [ 22.3918,  52.9416],
  

Train: 7257.61328125
tensor([[ 42.5396, 102.9549],
        [ 19.3191,  66.4928],
        [  9.0931, 110.3704],
        [ 48.3240, 145.2840]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 6613.8486328125
tensor([[-40.6626, 142.4924],
        [ 27.1684, 121.6536],
        [ 15.0888, 134.8999],
        [ 49.7771,  77.1786]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 8044.40087890625
tensor([[-31.3675, 109.6308],
        [  6.8826,  96.3223],
        [ 42.9893, 137.6539],
        [-32.6127, 123.2946]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 7423.75
tensor([[ -0.6495,  76.5243],
        [  7.1439,  89.4170],
        [  9.8670, 102.9679],
        [ 23.7359, 109.3292]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 4639.8564453125
tensor([[-4.7907e-02,  1.2985e+01],
        [ 3.0986e+01,  1.5821e+02],
        [-6.9749e+00,  7.3872e+01],
        [-4.6391e+01, -2.5759e+01]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 4310.03271484375
tensor([[ -91.8149,  -86.3577],
    

tensor([[-83.2386,   3.4107],
        [ 47.8053,   6.1969],
        [-51.4169,  34.3693],
        [ 28.8500,  42.3227]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1964.065185546875
tensor([[-14.2031,  28.5640],
        [ 20.0262,  24.6216],
        [ 37.0373,  12.2601],
        [ 49.6693,  22.8439]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 816.9822998046875
tensor([[-50.0854,  39.5917],
        [ 41.8170,  29.2019],
        [-18.4312,  55.9509],
        [ -4.1415,  -5.5437]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1274.4456787109375
tensor([[-53.9661,  17.1742],
        [-26.4179, -10.1713],
        [-52.9562,  -4.0754],
        [-21.5350,  -3.5174]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 913.219482421875
tensor([[  10.6303,  -42.5783],
        [  45.8519,  -19.6620],
        [ -13.0032,  -30.0720],
        [  42.7008, -153.3509]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 3853.5234375
tensor([[-48.8628,  13.0370],
        [-66.1678,  20.9092],
  

Train: 38161.50390625
tensor([[ 93.2744,  80.6079],
        [  3.7370,  66.3174],
        [ 82.0089,  27.2049],
        [103.4253,  67.2923]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 5287.5419921875
tensor([[ 56.2271, -11.1476],
        [ 42.1304,  37.3004],
        [ 99.0219,  57.2335],
        [ 17.4592,  58.6720]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2910.036376953125
tensor([[-4.9638e+01, -6.6064e-01],
        [-2.3625e+01,  4.9545e+00],
        [-2.6286e+00, -2.6826e+01],
        [-4.5094e-02, -3.4143e+01]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 617.413818359375
tensor([[-132.7544,  -51.5952],
        [-122.3893,  -46.5279],
        [-128.3807,   26.3030],
        [-100.5264,  -20.5340]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 8141.30224609375
tensor([[ 64.1861,  -0.5710],
        [ 23.9636, -10.7487],
        [ 28.5765, -59.7361],
        [ 20.8339, -29.0589]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1309.18212890625
tensor([[ 50.407

Train: 835.68408203125
tensor([[ 43.9177, -27.1872],
        [-48.8854, -47.8470],
        [-24.0311, -95.1634],
        [  4.0032, -61.7846]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 2601.7431640625
tensor([[-64.0061, -13.8623],
        [-25.6374,  -0.3358],
        [-10.5626,   8.6095],
        [-21.1512, -45.3803]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 954.8463134765625
tensor([[-48.9291,  -4.8984],
        [-25.2382,  19.4296],
        [-20.6566,  36.4375],
        [ -9.5548,  25.4800]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 740.9303588867188
tensor([[ 36.9446,  20.8278],
        [ 38.8284,  24.1836],
        [-40.4974,   6.3909],
        [-13.9045,  10.5165]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 734.5012817382812
tensor([[  4.2650,   9.5310],
        [-13.8607,  49.3213],
        [ 20.1020,  39.4591],
        [ 70.5427,  42.8104]], device='cuda:0', grad_fn=<SubBackward0>)
Train: 1437.98193359375
tensor([[-17.9597, -31.3487],
        [ 34.95